### ISSUE TITLE
Replace Blendid with our own setup

### ISSUE THREAD

**Issue by chrismlusk** [onedesign/craft-starter#46]
See #39

---

## Requirements

- [x] hot reloading every change
- [x] JS source maps, linting, minification
- [ ] font optimization
- [ ] image optimization
- [x] ~image revving that works with background images in Sass~
- [ ] asset revving on all files
- [x] Sass source maps, linting, autoprefixer, minification
- [x] IP or URL for mobile phone testing
- [ ] favicon and static assets copied to `dist`
- [x] key settings configurable via `.env` or `config.js`

**Comment by brianjhanson** [comment]
>  image revving that works with background images in Sass

Does this / did this work with Blendid? I'm not sure we can easily do something like this without switching to a Webpack based build because it would require your SCSS files to know how to resolve a path based on the manifest file. There might be a PostCSS plugin to do it, but I don't think I've seen one. 

> everything configurable via .env
Probably best to be more specific about what "everything" means here.

**Comment by MikeMcChillin** [comment]
`everything configurable via .env`
Just means no hardcoding things like `http://localhost:3000` - if it's a variable, it should be configured either by an `.env` or by some sort of `config.js`

**Comment by brianjhanson** [comment]
Closed via #39
