### ISSUE TITLE
Move Craft into `app` directory

### ISSUE THREAD

**Issue by chrismlusk** [onedesign/craft-starter#51]
But let's wait on #39 to be pushed through first.

**Comment by flynnt** [comment]
#39 is in now, so we can probably revisit this suggestion that I very much approve.

**Comment by brianjhanson** [comment]
I tried this in #52 and the issue is that it breaks the `composer create-project` command because that command will look for a `composer.json` file within the root of whatever repo we point it to. 

I've been trying to think of what the solution is and I don't have a great one. It might be better to turn this into a [repository template](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template) rather than using the `create-project` command. I haven't dug into that though.
